[Gameplay]
	# Whether to add local marker for the spot where the player died.
	# default: true
	autoDeathMarker = true
	# Whether to add global markers for NPC villages.
	# default: false
	autoVillageMarkers = false
	# Whether to add global markers for Nether Portals.
	# default: true
	autoNetherPortalMarkers = true
[Interface]
	# default: false
	doScaleMarkers = false
	# Default zoom level
	# The number corresponds to the size of a block on the map relative to the size of a GUI pixel
	# Preferrably a power of 2.
	# range[0.001953125, 16.0]
	# default: 0.5
	defaultScale = 0.5
	# Minimum zoom level
	# The number corresponds to the size of a block on the map relative to the size of a GUI pixel
	# Preferrably a power of 2
	# Smaller values may decrease performance!
	# range[0.001953125, 16.0]
	# default: 0.03125
	minScale = 0.03125
	# Maximum zoom level
	# The number corresponds to the size of a block on the map relative to the size of a GUI pixel
	# Preferrably a power of 2.
	# range[0.001953125, 16.0]
	# default: 4.0
	maxScale = 4.0
	# If false (by default), then mousewheel up is zoom in, mousewheel down is zoom out.
	# If true, then the direction is reversed.
	# default: false
	doReverseWheelZoom = false
	# Which verb to use to describe player death locations.
	# options: GRAVE, ITEMS, DIED, EUPHEMISMS
	# default: EUPHEMISMS
	graveStyle = "EUPHEMISMS"
[Performance]
	# The radius of the area around the player which is scanned by the Atlas at regular intervals.
	# Note that this will not force faraway chunks to load, unless forceChunkLoading is enabled.
	# Lower value gives better performance.
	# default: 11
	scanRadius = 11
	# Force loading of chunks within scan radius even if it exceeds regular chunk loading distance.
	# Enabling this may SEVERELY decrease performance!
	# default: false
	forceChunkLoading = false
	# Time in seconds between two scans of the area.
	# Higher value gives better performance.
	# default: 1.0
	newScanInterval = 1.0
	# Whether to rescan chunks in the area that have been previously mapped
	# This is useful in case of changes in coastline (including small ponds of water and lava), or if land disappears completely (for sky worlds).
	# Disable for better performance.
	# default: true
	doRescan = true
	# The number of area scans between full rescans.
	# Higher value gives better performance.
	# range[1, 1000]
	# default: 4
	rescanRate = 4
	# The maximum number of markers a particular atlas can hold.
	# range[0, 2147483647]
	# default: 1024
	markerLimit = 1024
	# Whether to perform additional scanning to locate small ponds of water or lava.
	# Disable for better performance.
	# default: true
	doScanPonds = true
	# Whether to perform additional scanning to locate ravines.
	# Disable for better performance.
	# default: true
	doScanRavines = true
	# If true, map render time will be output.
	# default: false
	debugRender = false
	# If true, all resource pack loading information will be logged during start and reload.
	# default: false
	resourcePackLogging = false
