
[dimension]
	#Determines if dimensionsList contains allowed dimensions or denied dimensions.
	#Allowed Values: DENY, ALLOW
	dimensionsListType = "DENY"
	#Dimensions for empowered undead.
	dimensionsList = []

[vulnerability]
	#The number of seconds that vulnerability from fire lasts.
	#Range: 0 ~ 100
	fireVulnerableDuration = 3
	#The materials that will be considered holy.
	holyMaterials = ["silver"]
	#The number of seconds that vulnerability from holy sources lasts.
	#Range: 0 ~ 100
	holyVulnerableDuration = 10

[undying]
	#The undying bonus speed modifier as a percent increase.
	#Range: 0 ~ 1000
	speedModifier = 15
	#The percent damage reduction against non-vulnerable damage dealt by mobs.
	#Range: 0 ~ 100
	damageReductionVsMobs = 80
	#The percent damage reduction against non-vulnerable damage.
	#Range: 0 ~ 100
	damageReduction = 80
	#The undying natural health regeneration in half-hearts per second.
	#Range: 0 ~ 1000
	healthRegeneration = 1
	#If enabled, default undead creatures will be given the undying trait.
	giveDefaultUndeadUndying = true

