[flavor_groups.rendering_mod]
name = "Extra Client Options"
description = "Which client mods you'd like to use.\nIncreases or decreases performance depending on choices."
side = "client"

[[flavor_groups.rendering_mod.choices]]
id = "default"
name = "Default"
description = "Recommended Options."

[[flavor_groups.rendering_mod.choices]]
id = "performance"
name = "Performance"

description = "Instdefaults only the important performance mods on client, and general utility. Doesn't instdefault any fancy rendering that may slow down."
[[flavor_groups.rendering_mod.choices]]
id = "extra"
name = "Extra"
description = "Recommended Options + Distant Horizons! + New Music! (May cause lag or performance issues.)"

[[flavor_groups.rendering_mod.choices]]
id = "no_rendering_mods"
description = "No rendering mods. No extra mods. Reduces Performance. May be useful for testing. Not Recommended"
name = "None"

[metafile.sodium]
flavors = ["performance", "default", "extra"]
[metafile.sodium-extra]
flavors = ["performance", "default", "extra"]
[metafile.indium]
flavors = ["performance", "default", "extra"]
[metafile.iris]
flavors = ["performance", "default", "extra"]
[metafile.jsonem]
flavors = ["performance", "default", "extra"]
[metafile.dynamic-fps]
flavors = ["performance", "default", "extra"]
[metafile.fast-paintings]
flavors = ["performance", "default", "extra"]
[metafile.borderless-mining]
flavors = ["performance", "default", "extra"]
[metafile.immediatly_fast]
flavors = ["performance", "default", "extra"]
[metafile.jei]
flavors = ["performance", "default", "extra"]
[metafile.nvidium]
flavors = ["performance", "default", "extra"]
[metafile.moreculling]
flavors = ["performance", "default", "extra"]
[metafile.morecullingextra]
flavors = ["performance", "default", "extra"]
[metafile.held-item-tooltips]
flavors = ["performance", "default", "extra"]
[metafile.modelfix]
flavors = ["performance", "default", "extra"]
[metafile.serious-player-animations]
flavors = ["performance", "default", "extra"]
[metafile.exodrium]
flavors = ["performance", "default", "extra"]
[metafile.raknetify]
flavors = ["performance", "default", "extra"]
[metafile.konkrete]
flavors = ["performance", "default", "extra"]
[metafile.melody]
flavors = ["performance", "default", "extra"]
[metafile.invmove]
flavors = ["performance", "default", "extra"]

[metafile.fancymenu]
flavors = ["default", "extra"]
[metafile.cit-resewn]
flavors = ["default", "extra"]
[metafile.continuity]
flavors = ["default", "extra"]
[metafile.fabricskyboxes]
flavors = ["default", "extra"]
[metafile.lambdynamiclights]
flavors = ["default", "extra"]
[metafile.charmonium]
flavors = ["default", "extra"]
[metafile.skinshuffle]
flavors = ["default", "extra"]
[metafile.cameraoverhaul]
flavors = ["default", "extra"]
[metafile.nicer-skies]
flavors = ["default", "extra"]
[metafile.leawind-third-person]
flavors = ["default", "extra"]
[metafile.presence-footsteps]
flavors = ["default", "extra"]
[metafile.blur]
flavors = ["default", "extra"]
[metafile.overflowing-bars]
flavors = ["default", "extra"]

[metafile.distanthorizons]
flavors = ["extra"]
[metafile.medieval-music]
flavors = ["extra"]
[metafile.biome-music]
flavors = ["extra"]
